### ISSUE TITLE
nose2django does not work with Django 1.6.1

### ISSUE THREAD

**Issue by thedrow** [bretth/nose2django#2]
```
Traceback (most recent call last):
  File "/home/omer/.virtualenvs/restapi/bin/nose2", line 9, in <module>
    load_entry_point('nose2==0.5.0', 'console_scripts', 'nose2')()
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2/main.py", line 284, in discover
    return main(*args, **kwargs)
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2/main.py", line 98, in __init__
    super(PluggableTestProgram, self).__init__(**kw)
  File "/home/omer/.pyenv/versions/2.7.4/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2/main.py", line 260, in runTests
    self.result = runner.run(self.test)
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2/runner.py", line 45, in run
    self.session.hooks.startTestRun(event)
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2/events.py", line 224, in __call__
    result = getattr(plugin, self.method)(event)
  File "/home/omer/.virtualenvs/restapi/lib/python2.7/site-packages/nose2django/nose2django.py", line 20, in startTestRun
    from django.test.simple import reorder_suite, DjangoTestSuiteRunner
ImportError: cannot import name reorder_suite
```

**Comment by harmon** [comment]
Got that too:  https://github.com/rwillmer/django-behave/pull/16
